# Generated by Django 4.2.1 on 2023-06-11 22:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, unique=True)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(max_length=2000)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='fecha de publicación')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.articuloscategoria', verbose_name='Categoría')),
            ],
        ),
    ]
