# Generated by Django 4.2.1 on 2023-06-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_articulos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'Articulo', 'verbose_name_plural': 'Articulos'},
        ),
    ]
